FROM node:lts-slim 

# Create app directory
WORKDIR /server

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

ENV DATABASE_URL=postgres://postgres:possystem1001446301!@db:5432/pos_system_db

# Expose port
EXPOSE 3000

# Start the app
RUN npm run start

